import type { ClosetItem } from './types';

export const mockClosetItems: ClosetItem[] = [
  {
    id: 1,
    name: 'White Cotton T-Shirt',
    category: 'Tops',
    color: 'White',
    season: ['All'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'white tshirt',
    lastWorn: '2023-10-15',
  },
  {
    id: 2,
    name: 'Blue Denim Jeans',
    category: 'Bottoms',
    color: 'Blue',
    season: ['All'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'blue jeans',
    lastWorn: '2023-10-18',
  },
  {
    id: 3,
    name: 'Black Leather Jacket',
    category: 'Outerwear',
    color: 'Black',
    season: ['Autumn', 'Winter'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'leather jacket',
  },
  {
    id: 4,
    name: 'Floral Sundress',
    category: 'Dresses',
    color: 'Multicolor',
    season: ['Summer'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'floral dress',
    lastWorn: '2023-08-20',
  },
  {
    id: 5,
    name: 'White Sneakers',
    category: 'Shoes',
    color: 'White',
    season: ['All'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'white sneakers',
    lastWorn: '2023-10-20',
  },
  {
    id: 6,
    name: 'Tan Trench Coat',
    category: 'Outerwear',
    color: 'Tan',
    season: ['Spring', 'Autumn'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'trench coat',
    lastWorn: '2023-05-10',
  },
  {
    id: 7,
    name: 'Black Trousers',
    category: 'Bottoms',
    color: 'Black',
    season: ['All'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'black trousers',
  },
  {
    id: 8,
    name: 'Gray Hoodie',
    category: 'Tops',
    color: 'Gray',
    season: ['All'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'gray hoodie',
    lastWorn: '2023-10-19',
  },
    {
    id: 9,
    name: 'Brown Loafers',
    category: 'Shoes',
    color: 'Brown',
    season: ['All'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'brown loafers',
  },
  {
    id: 10,
    name: 'Silk Scarf',
    category: 'Accessories',
    color: 'Red',
    season: ['All'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'silk scarf',
  },
  {
    id: 11,
    name: 'Denim Shorts',
    category: 'Bottoms',
    color: 'Blue',
    season: ['Summer'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'denim shorts',
  },
  {
    id: 12,
    name: 'Knit Sweater',
    category: 'Tops',
    color: 'Cream',
    season: ['Winter'],
    imageUrl: 'https://placehold.co/400x600/png',
    dataAiHint: 'knit sweater',
  },
];
