server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/styleai_wardrobe
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# AI Service Configuration
ai:
  openai:
    api-key: ${OPENAI_API_KEY:your-openai-api-key}
    base-url: https://api.openai.com/v1
  
logging:
  level:
    com.styleai: DEBUG
    org.springframework.web: DEBUG

# CORS Configuration
cors:
  allowed-origins: http://localhost:9002,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"